before_script: cd simppriv-api/
before_install: - chmod +x gradlew

language: java

before_cache:
  - rm -f  simppriv-api.gradle/caches/modules-2/modules-2.lock
  - rm -fr simppriv-api/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - simppriv-api/.gradle/caches/
    - simppriv-api/.gradle/wrapper/

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
